/**
 * Compact building-code knowledge base with clause references. Values are summaries of
 * commonly used provisions — always verify against the official code text.
 */
export interface CodeClause { id: string; code: string; clause: string; topic: string; text: string; keywords: string[] }

/** Display order of countries in the Code library (Bangladesh first, as requested). */
export const COUNTRY_ORDER = ["Bangladesh", "India", "China", "USA", "Pakistan", "Nepal", "Europe", "International"] as const;
export type Country = (typeof COUNTRY_ORDER)[number];

export function countryOf(code: string): Country {
  const c = code.toUpperCase();
  if (c.startsWith("BNBC") || c.includes("RAJUK")) return "Bangladesh";
  if (/^(IS |IRC|NBC 2016|SP:)/.test(c) || c.startsWith("IS ")) return "India";
  if (c.startsWith("GB ")) return "China";
  if (/^(ACI|ASCE|AISC|IBC|NDS)/.test(c)) return "USA";
  if (/^(BCP|PAKISTAN)/.test(c)) return "Pakistan";
  if (/^NBC \d{3}/.test(c) || c.includes("NEPAL")) return "Nepal";
  if (/^(EN |EUROCODE|BS )/.test(c)) return "Europe";
  return "International";
}
export const countryRank = (code: string) => COUNTRY_ORDER.indexOf(countryOf(code));

export const CODE_CLAUSES: CodeClause[] = [
  // IS 456:2000
  { id: "is456-26.4", code: "IS 456:2000", clause: "26.4.2 / Table 16", topic: "Nominal cover", text: "Nominal cover for mild exposure 20 mm, moderate 30 mm, severe 45 mm, very severe 50 mm, extreme 75 mm. For footings minimum cover 50 mm. Cover may be reduced by 5 mm for slabs in mild exposure with bars ≤ 12 mm.", keywords: ["cover", "exposure", "footing", "durability"] },
  { id: "is456-26.5.1.1", code: "IS 456:2000", clause: "26.5.1.1", topic: "Minimum tension steel in beams", text: "As/(b·d) ≥ 0.85/fy. Maximum tension reinforcement 4% of gross area (cl. 26.5.1.1(b)).", keywords: ["minimum steel", "beam", "tension", "maximum steel"] },
  { id: "is456-26.5.1.5", code: "IS 456:2000", clause: "26.5.1.5 / 26.5.1.6", topic: "Shear reinforcement in beams", text: "Maximum stirrup spacing 0.75·d for vertical stirrups (d for inclined), not exceeding 300 mm. Minimum shear reinforcement Asv/(b·sv) ≥ 0.4/(0.87·fy).", keywords: ["stirrup", "shear", "spacing", "minimum shear"] },
  { id: "is456-26.5.2.1", code: "IS 456:2000", clause: "26.5.2.1", topic: "Minimum steel in slabs", text: "Mild steel bars: 0.15% of total cross-sectional area; high-strength deformed bars (Fe415/Fe500): 0.12%. Max bar spacing: 3d or 300 mm for main bars; 5d or 450 mm for distribution bars.", keywords: ["slab", "minimum steel", "distribution", "spacing"] },
  { id: "is456-26.5.3.1", code: "IS 456:2000", clause: "26.5.3.1", topic: "Columns longitudinal reinforcement", text: "Longitudinal steel 0.8% to 6% of gross area (4% practical max for lapping). Minimum 4 bars in rectangular columns, 6 in circular; minimum bar diameter 12 mm. Ties: diameter ≥ max(6 mm, ¼ largest bar), pitch ≤ min(least lateral dimension, 16 × smallest bar dia, 300 mm).", keywords: ["column", "ties", "longitudinal", "minimum steel", "pitch"] },
  { id: "is456-23.2.1", code: "IS 456:2000", clause: "23.2.1", topic: "Span to effective depth ratios (deflection)", text: "Basic values for spans ≤ 10 m: cantilever 7, simply supported 20, continuous 26. Multiply by modification factors for tension steel (Fig. 4), compression steel (Fig. 5) and flanged sections (Fig. 6). For spans > 10 m multiply by 10/span (except cantilevers).", keywords: ["deflection", "span depth", "l/d", "cantilever", "continuous"] },
  { id: "is456-38.1", code: "IS 456:2000", clause: "38.1 / Annex G", topic: "Limiting neutral axis and Mu,lim", text: "xu,max/d = 0.53 (Fe250), 0.48 (Fe415), 0.46 (Fe500). Mu,lim = 0.36·fck·b·xu,max·(d − 0.42·xu,max). Design stress block: 0.36·fck·b·xu; lever arm d − 0.42·xu.", keywords: ["limit state", "flexure", "neutral axis", "mu lim", "stress block"] },
  { id: "is456-39.3", code: "IS 456:2000", clause: "39.3", topic: "Short axially loaded columns", text: "Pu = 0.4·fck·Ac + 0.67·fy·Asc, valid when minimum eccentricity emin = l/500 + D/30 ≥ 20 mm does not exceed 0.05·D.", keywords: ["column", "axial", "short column", "eccentricity"] },
  { id: "is456-40", code: "IS 456:2000", clause: "40.1 / Table 19 / Table 20", topic: "Shear design", text: "τv = Vu/(b·d). Design shear strength τc from Table 19 (depends on fck and pt = 100As/bd). If τv > τc provide shear reinforcement for Vus = Vu − τc·b·d: sv = 0.87·fy·Asv·d/Vus. τv must not exceed τc,max (Table 20: 2.8 MPa for M20, 3.1 for M25, 3.5 for M30).", keywords: ["shear", "tau c", "stirrup design"] },
  { id: "is456-36.4", code: "IS 456:2000", clause: "36.4.2 / Table 18", topic: "Partial safety factors & load combinations", text: "Limit state of collapse: 1.5(DL + LL); 1.2(DL + LL ± EL/WL); 1.5(DL ± EL/WL); 0.9DL ± 1.5EL/WL. Material factors γm: concrete 1.5, steel 1.15.", keywords: ["load combination", "partial safety", "factor", "1.5"] },
  { id: "is456-34.1", code: "IS 456:2000", clause: "34.1 / 34.2.4.1", topic: "Footings", text: "Bending moment critical section at the face of column. One-way shear critical section at distance d from column face; two-way (punching) at d/2 from the column periphery with permissible ks·τc where τc = 0.25·√fck and ks = 0.5 + βc ≤ 1. Minimum thickness at edge 150 mm (on soil).", keywords: ["footing", "punching", "one way shear", "critical section"] },
  { id: "is456-26.2.1", code: "IS 456:2000", clause: "26.2.1", topic: "Development length", text: "Ld = φ·σs/(4·τbd); τbd for M20 = 1.2 MPa (plain), ×1.6 for deformed bars, ×1.25 in compression. Typical Ld ≈ 47φ (M20/Fe415), 40φ (M25/Fe415).", keywords: ["development length", "anchorage", "bond", "ld"] },
  { id: "is456-26.3.2", code: "IS 456:2000", clause: "26.3.2 / 26.3.3", topic: "Bar spacing", text: "Minimum clear horizontal distance between bars: greater of bar diameter and nominal max aggregate size + 5 mm. Maximum spacing of tension bars in beams (Table 15): 300 mm for Fe250, 180 mm for Fe415, 150 mm for Fe500 (0% redistribution).", keywords: ["spacing", "clear distance", "crack width"] },
  { id: "is875-2", code: "IS 875 (Part 2):1987", clause: "Table 1", topic: "Imposed floor loads", text: "Residential 2.0 kN/m²; office 2.5–4.0; classrooms 3.0; corridors/stairs 3.0–5.0; shops 4.0; storage 5.0 per m height (min 7.5); garages (light) 2.5–5.0. Partitions: additional 1 kN/m² typical.", keywords: ["live load", "imposed load", "floor load", "residential", "office"] },
  { id: "is875-1", code: "IS 875 (Part 1):1987", clause: "Table 1", topic: "Unit weights", text: "Reinforced concrete 25 kN/m³; plain concrete 24; brick masonry 19–20; steel 78.5; timber 6–8; floor finish (screed + tiles) ≈ 1.0–1.5 kN/m²; 115 mm brick wall ≈ 2.2 kN/m per m height; 230 mm ≈ 4.4 kN/m per m height.", keywords: ["dead load", "unit weight", "density", "brick", "concrete"] },
  { id: "is1893", code: "IS 1893 (Part 1):2016", clause: "6.4.2 / Table 3", topic: "Seismic base shear", text: "Ah = (Z/2)·(Sa/g)/(R/I); VB = Ah·W. Zone factors Z: II 0.10, III 0.16, IV 0.24, V 0.36. R = 3 (OMRF), 5 (SMRF); I = 1.0 normal, 1.2 important, 1.5 critical. Approx. period T = 0.075·h^0.75 (RC MRF), 0.085·h^0.75 (steel MRF), 0.09·h/√d (with infills).", keywords: ["seismic", "earthquake", "base shear", "zone factor", "response reduction"] },
  { id: "is800-8.2", code: "IS 800:2007", clause: "8.2.1.2", topic: "Laterally supported beams", text: "Md = βb·Zp·fy/γm0 ≤ 1.2·Ze·fy/γm0 (simply supported), with γm0 = 1.10; βb = 1.0 for plastic/compact sections. Deflection limit for floor beams L/300 (elastic cladding) per Table 6.", keywords: ["steel beam", "plastic moment", "gamma m0", "deflection limit"] },
  { id: "is800-7", code: "IS 800:2007", clause: "7.1.2 / Table 9", topic: "Compression members", text: "Pd = Ae·fcd, fcd from buckling curves a/b/c/d (Table 7) depending on section type and axis. Slenderness ratio limit 180 for members carrying compressive loads from dead + imposed (Table 3).", keywords: ["column", "buckling", "slenderness", "compression"] },
  // ACI 318-19
  { id: "aci-9.6.1.2", code: "ACI 318-19", clause: "9.6.1.2", topic: "Minimum flexural reinforcement in beams", text: "As,min = max(0.25·√f'c/fy, 1.4/fy)·bw·d (SI, MPa).", keywords: ["minimum steel", "beam", "flexure"] },
  { id: "aci-21.2", code: "ACI 318-19", clause: "21.2.2 / Table 21.2.2", topic: "Strength reduction factors", text: "φ = 0.90 tension-controlled flexure (εt ≥ 0.005), 0.65 compression-controlled tied columns (0.75 spiral), 0.75 shear and torsion, 0.65 bearing.", keywords: ["phi", "strength reduction", "factor"] },
  { id: "aci-5.3", code: "ACI 318-19", clause: "5.3.1", topic: "Load combinations", text: "U = 1.4D; 1.2D + 1.6L + 0.5(Lr or S or R); 1.2D + 1.6(Lr or S or R) + (1.0L or 0.5W); 1.2D + 1.0W + 1.0L + 0.5(Lr or S or R); 1.2D + 1.0E + 1.0L + 0.2S; 0.9D + 1.0W; 0.9D + 1.0E.", keywords: ["load combination", "factored", "1.2D", "1.6L"] },
  { id: "aci-22.5", code: "ACI 318-19", clause: "22.5.5.1", topic: "Concrete shear strength", text: "Vc = 0.17·λ·√f'c·bw·d (SI) for Av ≥ Av,min; otherwise Vc = 0.66·λ·(ρw)^(1/3)·√f'c·bw·d (with size effect λs). Vs ≤ 0.66·√f'c·bw·d. Vu ≤ φ(Vc + Vs), φ = 0.75.", keywords: ["shear", "vc", "stirrups"] },
  { id: "aci-9.7.6", code: "ACI 318-19", clause: "9.7.6.2.2", topic: "Stirrup spacing", text: "Max spacing d/2 or 600 mm when Vs ≤ 0.33√f'c·bw·d; halve to d/4 or 300 mm when Vs exceeds that. Av,min = max(0.062√f'c, 0.35)·bw·s/fyt.", keywords: ["stirrup", "spacing", "minimum shear reinforcement"] },
  { id: "aci-10.6", code: "ACI 318-19", clause: "10.6.1.1", topic: "Column reinforcement limits", text: "Longitudinal reinforcement 0.01·Ag ≤ Ast ≤ 0.08·Ag; minimum 4 bars in rectangular tied columns, 6 in spiral. Tie spacing ≤ min(16 db, 48 dtie, least dimension).", keywords: ["column", "ties", "reinforcement ratio"] },
  { id: "aci-22.4", code: "ACI 318-19", clause: "22.4.2.2", topic: "Column axial capacity", text: "Pn,max = 0.80·[0.85·f'c·(Ag − Ast) + fy·Ast] for tied columns (0.85 for spiral); design strength φ·Pn,max with φ = 0.65 (tied).", keywords: ["column", "axial", "capacity"] },
  { id: "aci-20.5", code: "ACI 318-19", clause: "20.5.1.3 / Table 20.5.1.3.1", topic: "Concrete cover", text: "Cast against earth 75 mm; exposed to weather 50 mm (No.19 and larger) or 40 mm (No.16 and smaller); not exposed: slabs/walls 20 mm, beams/columns 40 mm.", keywords: ["cover", "concrete cover"] },
  { id: "aci-7.6.1", code: "ACI 318-19", clause: "7.6.1.1 / 24.4.3.2", topic: "Slab minimum reinforcement", text: "As,min = 0.0018·Ag for Grade 420 deformed bars (0.0020 for Grade 280/350); temperature/shrinkage spacing ≤ min(5h, 450 mm); flexural bar spacing ≤ min(3h, 450 mm).", keywords: ["slab", "shrinkage", "temperature", "minimum"] },
  { id: "aci-9.3.1", code: "ACI 318-19", clause: "Table 9.3.1.1 / 7.3.1.1", topic: "Minimum depth of beams and one-way slabs", text: "Beams (fy = 420): simply supported l/16, one end continuous l/18.5, both ends continuous l/21, cantilever l/8. One-way slabs: l/20, l/24, l/28, l/10 respectively.", keywords: ["minimum depth", "deflection", "span", "thickness"] },
  { id: "asce7-4", code: "ASCE 7-22", clause: "Table 4.3-1", topic: "Minimum uniformly distributed live loads", text: "Residential 1.92 kN/m² (40 psf); offices 2.40 (50 psf); corridors above first floor 3.83 (80 psf); assembly fixed seats 2.87 (60 psf), movable 4.79 (100 psf); light storage 6.00 (125 psf); parking 1.92 (40 psf); roofs 0.96 (20 psf).", keywords: ["live load", "psf", "residential", "office"] },
  // Eurocode 2
  { id: "ec2-9.2.1.1", code: "EN 1992-1-1", clause: "9.2.1.1", topic: "Minimum and maximum beam reinforcement", text: "As,min = 0.26·(fctm/fyk)·bt·d ≥ 0.0013·bt·d; As,max = 0.04·Ac.", keywords: ["minimum steel", "beam", "eurocode"] },
  { id: "ec2-4.4.1", code: "EN 1992-1-1", clause: "4.4.1 / Table 4.4N", topic: "Nominal cover", text: "cnom = cmin + Δcdev (Δcdev = 10 mm typical). cmin,dur for XC1 15 mm (S4), XC2/XC3 25 mm, XC4 30 mm, XD1/XS1 35 mm, XD2/XS2 40 mm, XD3/XS3 45 mm; cmin ≥ bar diameter.", keywords: ["cover", "exposure class", "durability"] },
  { id: "ec2-6.2.2", code: "EN 1992-1-1", clause: "6.2.2", topic: "Shear resistance without shear reinforcement", text: "VRd,c = [CRd,c·k·(100·ρl·fck)^(1/3)]·bw·d ≥ vmin·bw·d, CRd,c = 0.18/γc, k = 1 + √(200/d) ≤ 2.0, vmin = 0.035·k^1.5·√fck.", keywords: ["shear", "vrd,c", "eurocode"] },
  { id: "ec2-6.1", code: "EN 1992-1-1", clause: "6.1 / 3.1.7", topic: "Flexural design (rectangular stress block)", text: "K = M/(b·d²·fck); K' = 0.167 (no redistribution, δ = 1). z = d·[0.5 + √(0.25 − K/1.134)] ≤ 0.95d. As = M/(0.87·fyk·z) with fyd = fyk/1.15, fcd = αcc·fck/1.5 (αcc = 0.85 UK NA, 1.0 recommended).", keywords: ["flexure", "lever arm", "K", "eurocode"] },
  { id: "ec2-9.3", code: "EN 1992-1-1", clause: "9.3.1.1", topic: "Slab reinforcement spacing", text: "Max spacing of principal reinforcement 3h ≤ 400 mm; secondary 3.5h ≤ 450 mm. Secondary reinforcement ≥ 20% of principal.", keywords: ["slab", "spacing", "secondary"] },
  { id: "ec2-9.5", code: "EN 1992-1-1", clause: "9.5.2 / 9.5.3", topic: "Column reinforcement", text: "As,min = max(0.10·NEd/fyd, 0.002·Ac); As,max = 0.04·Ac (0.08 at laps). Min bar 8 mm (12 mm UK NA); links ≥ max(6 mm, ¼ largest bar), spacing ≤ min(20·φmin, lesser column dimension, 400 mm).", keywords: ["column", "links", "minimum steel"] },
  { id: "ec2-7.4.2", code: "EN 1992-1-1", clause: "7.4.2 / Table 7.4N", topic: "Span/depth ratios", text: "Basic l/d for ρ = 0.5% (K factor): simply supported 20 (K=1.0), end span 26 (K=1.3), interior span 30 (K=1.5), flat slab 24 (K=1.2), cantilever 8 (K=0.4). Multiply by 310/σs and 7/leff for leff > 7 m.", keywords: ["deflection", "span depth", "eurocode"] },
  { id: "ec0-6.4.3", code: "EN 1990", clause: "6.4.3.2 / Eq. 6.10", topic: "ULS load combination", text: "Ed = 1.35·Gk + 1.5·Qk,1 + Σ 1.5·ψ0,i·Qk,i (persistent/transient). Alternatives 6.10a/6.10b: 1.35Gk + 1.5ψ0Qk ; 0.925×1.35Gk + 1.5Qk (UK NA ξ = 0.925).", keywords: ["load combination", "1.35", "1.5", "eurocode"] },
  { id: "ec1-6.3", code: "EN 1991-1-1", clause: "Table 6.2", topic: "Imposed loads on floors", text: "Category A (residential) 1.5–2.0 kN/m²; B (offices) 2.0–3.0; C1 (cafes) 2.0–3.0, C3 (corridors) 3.0–5.0, C5 (crowds) 5.0–7.5; D1 (shops) 4.0–5.0; E1 (storage) 7.5; partitions add 0.5–1.2 kN/m² depending on self-weight.", keywords: ["imposed load", "live load", "eurocode", "category"] },
  // Architecture / building bye-laws (NBC 2016)
  { id: "nbc-12.2", code: "NBC 2016 Part 3", clause: "12.2 / 12.3 / 12.4", topic: "Minimum room sizes", text: "Habitable room ≥ 9.5 m² (min width 2.4 m); where two rooms, one ≥ 9.5 m² and other ≥ 7.5 m². Kitchen ≥ 5.0 m² (4.5 m² with separate dining), min width 1.8 m. Bathroom ≥ 1.8 m² (min 1.2 m wide); WC ≥ 1.1 m² (min 0.9 m); combined bath+WC ≥ 2.8 m². Store ≥ 3.0 m². Garage 3.0 × 4.5 m min.", keywords: ["room size", "minimum area", "bedroom", "kitchen", "bathroom", "architecture", "bye law"] },
  { id: "nbc-12.1", code: "NBC 2016 Part 3", clause: "12.1 / 12.12", topic: "Ceiling height and ventilation", text: "Habitable rooms: clear height ≥ 2.75 m (2.4 m for air-conditioned); kitchen 2.75 m; bath/WC 2.2 m. Openings for light and ventilation ≥ 1/10 of floor area (habitable), 1/12 in hot-dry regions with verandah; kitchen ventilation via window ≥ 1 m² or exhaust.", keywords: ["ceiling height", "ventilation", "window area", "light", "architecture"] },
  { id: "nbc-8.5", code: "NBC 2016 Part 3", clause: "8.5 / Table 6", topic: "Setbacks and coverage (typical)", text: "Setbacks depend on plot size and road width per local bye-laws; NBC indicates front 1.5–3.0 m, side 1.0–1.5 m for plots up to 200 m²; ground coverage typically 60–75 % for small residential plots; FAR/FSI 1.5–2.5 typical (local authority governs).", keywords: ["setback", "coverage", "far", "fsi", "plot", "bye law"] },
  { id: "nbc-4-stair", code: "NBC 2016 Part 4", clause: "4.4.2 / 4.4.3", topic: "Staircases", text: "Residential internal stair: min width 1.0 m (0.75 m row housing), riser ≤ 190 mm, tread ≥ 250 mm; public buildings width ≥ 1.5 m, riser ≤ 150 mm, tread ≥ 300 mm; headroom ≥ 2.2 m; max 12–15 risers per flight; handrail height 0.9–1.0 m.", keywords: ["stair", "riser", "tread", "handrail", "architecture"] },
  { id: "nbc-doors", code: "NBC 2016 Part 3", clause: "12.20", topic: "Doors and corridors", text: "Door minimum clear width: main entrance 1.0 m, internal 0.9 m (0.75 m for bath/WC); height ≥ 2.0 m. Corridors/passages in residences ≥ 1.0 m wide (1.2 m preferred); accessible route ≥ 1.2 m (Part 3 Annex B).", keywords: ["door", "corridor", "passage", "width", "accessibility"] },
  // Bangladesh — BNBC 2020 (Part 6: Structural Design). Summaries; verify against the gazetted text.
  { id: "bnbc-2.3", code: "BNBC 2020 Part 6", clause: "Ch. 2, Table 6.2.3", topic: "Minimum live loads", text: "Residential (dwellings, apartments) 2.0 kN/m²; hotel rooms 2.0; offices 2.4; classrooms 2.0–3.0; corridors above ground floor 3.8 (4.8 for public buildings); shops (retail, ground floor) 4.8; storage light 6.0, heavy 12.0; car parking 2.4 (passenger cars); roofs (flat, accessible) 1.5; stairs/exits 4.8. Partition allowance ≥ 1.0 kN/m² where partitions may move.", keywords: ["bangladesh", "bnbc", "live load", "residential", "office", "shop", "imposed load"] },
  { id: "bnbc-2.5", code: "BNBC 2020 Part 6", clause: "Ch. 2, Sec. 2.5 / Fig. 6.2.24 / Table 6.2.14", topic: "Seismic zones", text: "Four seismic zones with zone coefficient Z: Zone 1 = 0.12 (Barisal, Khulna, Jessore, Rajshahi region), Zone 2 = 0.20 (Dhaka, Comilla, Pabna), Zone 3 = 0.28 (Chittagong, Rangpur, Bogra, Mymensingh), Zone 4 = 0.36 (Sylhet, Kurigram, Sunamganj). Site classes SA–SE (Eurocode-8 style). Design base shear V = Sa·W with Sa = (2/3)(Z·I/R)·Cs. Importance factor I = 1.0/1.25/1.5; response modification R per system (e.g. SMRF concrete 8, IMRF 5, OMRF 3).", keywords: ["bangladesh", "bnbc", "seismic", "earthquake", "zone coefficient", "dhaka", "sylhet", "chittagong", "base shear"] },
  { id: "bnbc-2.4", code: "BNBC 2020 Part 6", clause: "Ch. 2, Sec. 2.4 / Table 6.2.8", topic: "Basic wind speeds", text: "3-second gust basic wind speed Vb (m/s) at 10 m height, 50-year: Dhaka 65.7, Chittagong 80.0, Cox's Bazar 80.0, Khulna 73.3, Sylhet 61.1, Rajshahi 49.2, Rangpur 65.3, Barisal 78.7, Comilla 61.4, Mymensingh 67.4. Design pressure per ASCE 7-05 style procedure with exposure A/B/C and importance factors.", keywords: ["bangladesh", "bnbc", "wind speed", "wind load", "dhaka", "chittagong"] },
  { id: "bnbc-6", code: "BNBC 2020 Part 6", clause: "Ch. 6 (Strength Design of Concrete)", topic: "Concrete design basis", text: "Follows ACI 318 strength design: φ = 0.90 flexure (tension-controlled), 0.75 shear/torsion, 0.65 tied columns; combinations 1.4D; 1.2D + 1.6L + 0.5Lr; 1.2D + 1.0E + 1.0L; 0.9D + 1.0E etc. (Sec. 2.7). Minimum flexural steel As,min = max(0.25√f'c/fy, 1.4/fy)·bw·d; minimum cover 40 mm beams/columns (not exposed), 20 mm slabs, 75 mm cast against earth. Common materials: f'c 17–35 MPa (2500–5000 psi), Grade 60 / 500 MPa rebar.", keywords: ["bangladesh", "bnbc", "concrete", "phi", "load combination", "cover", "minimum steel"] },
  { id: "bnbc-3", code: "BNBC 2020 Part 6", clause: "Ch. 3 (Soils and Foundations), Table 6.3.1", topic: "Presumptive bearing capacity", text: "Allowable bearing pressure for preliminary design: soft clay 50–100 kPa, medium clay 100–200, stiff clay 200–400; loose sand 100–150, medium dense sand 150–300, dense sand 300–500; soft rock 800–1000. Minimum foundation depth 1.0 m below GL in general (1.5 m in expansive/flood-prone soils); SPT-based design and a geotechnical report are required for buildings over 3 storeys.", keywords: ["bangladesh", "bnbc", "bearing capacity", "soil", "foundation depth", "spt"] },
  { id: "bnbc-3-part", code: "BNBC 2020 Part 3", clause: "Ch. 1 – 3 (General building requirements)", topic: "Setbacks, FAR and room sizes (Bangladesh)", text: "Mandatory open spaces per Dhaka Mahanagar Imarat Nirman Bidhimala 2008 / BNBC: typical front setback 1.5 m (plot ≤ 134 m²) rising to 4.5 m for large plots; side/rear 1.0–3.0 m depending on plot size; FAR 3.15–6.5 and Maximum Ground Coverage 50–67.5% by plot size (RAJUK). Habitable room ≥ 9.3 m² (min side 2.5 m), kitchen ≥ 4.65 m², bath ≥ 1.8 m², WC ≥ 1.1 m²; clear height ≥ 2.75 m.", keywords: ["bangladesh", "rajuk", "setback", "far", "ground coverage", "room size", "dhaka", "bye law"] },
  // China — GB national standards. Summaries; verify against the official text (Chinese).
  { id: "gb50010-4", code: "GB 50010-2010 (2015)", clause: "4.1 / 4.2, Tables 4.1.4, 4.2.3", topic: "Material design strengths", text: "Concrete grades C15–C80; design compressive strength fc: C25 11.9, C30 14.3, C35 16.7, C40 19.1, C50 23.1 MPa; design tensile ft: C30 1.43, C40 1.71 MPa. Rebar design yield fy: HPB300 270, HRB400/HRBF400 360, HRB500 435 MPa. Ec: C30 3.0×10⁴, C40 3.25×10⁴ MPa.", keywords: ["china", "gb 50010", "concrete grade", "c30", "hrb400", "design strength"] },
  { id: "gb50010-8.5", code: "GB 50010-2010", clause: "8.5.1 / Table 8.5.1", topic: "Minimum reinforcement ratios", text: "Beam tension steel ρmin = max(0.20 %, 45·ft/fy %) (e.g. C30 + HRB400: max(0.20, 0.179) = 0.20 %); slabs same rule (0.15 % permitted for HRB400/500 in some cases); column total longitudinal ρmin = 0.55 % (HRB400), 0.50 % (HRB500), 0.60 % (HRB335) with min 0.2 % on each face; maximum 5 %.", keywords: ["china", "gb 50010", "minimum reinforcement", "beam", "column", "reinforcement ratio"] },
  { id: "gb50010-8.2", code: "GB 50010-2010", clause: "8.2.1 / Table 8.2.1", topic: "Concrete cover", text: "Minimum cover to outermost bar for design life 50 years: environment class I (indoor dry): slabs/walls 15 mm, beams/columns 20 mm; class IIa: 20 / 25 mm; IIb: 25 / 35 mm; IIIa: 30 / 40 mm; IIIb: 40 / 50 mm. Increase ×1.4 for 100-year design life; cover ≥ bar diameter.", keywords: ["china", "gb 50010", "cover", "environment class"] },
  { id: "gb50010-9.2", code: "GB 50010-2010", clause: "9.2.9 / Table 9.2.9", topic: "Stirrup spacing in beams", text: "Maximum stirrup spacing smax (V > 0.7ft·b·h0 / V ≤ 0.7ft·b·h0): h ≤ 300 mm: 150 / 200; 300 < h ≤ 500: 200 / 300; 500 < h ≤ 800: 250 / 350; h > 800: 300 / 400. Min stirrup dia 6 mm (h ≤ 800), 8 mm (h > 800); ρsv,min = 0.24·ft/fyv.", keywords: ["china", "gb 50010", "stirrup", "spacing", "shear"] },
  { id: "gb50009-5", code: "GB 50009-2012", clause: "5.1.1, Table 5.1.1", topic: "Uniform live loads", text: "Residential, dormitory, hotel, office, hospital ward 2.0 kN/m²; classroom 2.5; canteen/restaurant 2.5; shops, exhibition halls 3.5; stairs 2.0 (residential) – 3.5 (others); balconies 2.5–3.5; parking (cars, slab) 4.0; kitchens (residential) 2.0, commercial 4.0; non-accessible roofs 0.5, accessible 2.0.", keywords: ["china", "gb 50009", "live load", "residential", "office", "shop"] },
  { id: "gb55001-3", code: "GB 55001-2021 (supersedes GB 50009 factors)", clause: "3.1.13", topic: "Load combination factors", text: "Fundamental combination for ULS: γG = 1.3 for permanent loads (1.0 when favourable), γQ = 1.5 for variable loads (GB 50009-2012 used 1.2 and 1.4). Quasi-permanent/combination factors ψc 0.7 typical for live loads, 0.6 for wind.", keywords: ["china", "gb 55001", "load combination", "partial factor", "1.3", "1.5"] },
  { id: "gb50011-3", code: "GB 50011-2010 (2016)", clause: "3.2 / Table 3.2.2, 5.1.4", topic: "Seismic design basis", text: "Seismic fortification intensity 6, 7, 8, 9 with design basic acceleration 0.05g, 0.10g (0.15g), 0.20g (0.30g), 0.40g. Site classes I0, I1, II, III, IV with characteristic period Tg 0.20–0.90 s by design earthquake group. αmax (frequent earthquake): 0.04 (6), 0.08/0.12 (7), 0.16/0.24 (8), 0.32 (9). Frame concrete grade ≥ C30 for grade-1 seismic detailing; columns axial-load ratio limits 0.65–0.90 by grade.", keywords: ["china", "gb 50011", "seismic", "intensity", "acceleration", "site class"] },
  { id: "gb50007-5", code: "GB 50007-2011", clause: "5.2.4", topic: "Bearing capacity depth/width correction", text: "fa = fak + ηb·γ·(b − 3) + ηd·γm·(d − 0.5), where fak = characteristic bearing capacity from load tests/tables, b = foundation width (3 m ≤ b ≤ 6 m), d = embedment depth (m), ηb/ηd from Table 5.2.4 (e.g. silty clay ηb = 0.3, ηd = 1.6; dense sand ηb = 3.0, ηd = 4.4). Allowable settlement limits per Table 5.3.4 (e.g. 200 mm for framed buildings on medium soil).", keywords: ["china", "gb 50007", "bearing capacity", "foundation", "correction", "settlement"] },
  // Pakistan — Building Code of Pakistan (BCP-SP 2007 / 2021 revision). Summaries; verify against the official text.
  { id: "bcp-seismic-zones", code: "BCP-SP 2021 (Pakistan)", clause: "Ch. 2 / Fig. 2.1, Table 2.1", topic: "Seismic zones", text: "Five zones by peak ground acceleration: Zone 1 = 0.05–0.08g, Zone 2A = 0.08–0.16g, Zone 2B = 0.16–0.24g, Zone 3 = 0.24–0.32g, Zone 4 > 0.32g. Typical: Karachi 2B, Lahore 2A, Islamabad/Rawalpindi 2B, Peshawar 2B–3, Quetta 4, Muzaffarabad 4. Design follows UBC-97-type seismic coefficients (Ca, Cv by soil type SA–SE) with R factors per structural system.", keywords: ["pakistan", "bcp", "seismic zone", "karachi", "lahore", "islamabad", "quetta", "earthquake"] },
  { id: "bcp-concrete", code: "BCP-SP 2021 (Pakistan)", clause: "Ch. 21 (Concrete) / Ch. 16 (Loads)", topic: "Concrete design and loads basis", text: "Concrete design adopts ACI 318 (strength design: φ 0.90 flexure, 0.75 shear, 0.65 tied columns; combinations 1.2D + 1.6L etc.). Loads follow ASCE 7/IBC values: residential 1.9 kN/m² (40 psf), offices 2.4 (50 psf), corridors 3.8 (80 psf), stairs 4.8 (100 psf). Seismic detailing (special moment frames) mandatory in Zones 3 and 4.", keywords: ["pakistan", "bcp", "concrete", "live load", "aci", "load combination"] },
  { id: "bcp-energy", code: "BCP – Energy Provisions 2011 / Building Code of Pakistan (Fire Safety 2016)", clause: "General", topic: "Other parts", text: "Energy Provisions 2011 set envelope U-values and lighting power densities for commercial buildings; Fire Safety Provisions 2016 set egress widths (min 1.1 m corridors in assembly), fire separation and sprinkler requirements. Local building bye-laws (KDA/LDA/CDA) govern setbacks, FAR and plot coverage.", keywords: ["pakistan", "fire safety", "energy", "bye law", "setback"] },
  // Nepal — Nepal National Building Code (NBC). Summaries; verify against the official text.
  { id: "nbc105-2020", code: "NBC 105:2020 (Nepal)", clause: "4.1 / Table 4.1, 5.1", topic: "Seismic design basis", text: "Seismic zoning factor Z from the 2020 map: 0.25 (far west/east lowlands) to 0.40 (parts of the Terai/mid-hills); Kathmandu Valley Z = 0.35. Importance factor I = 1.0 (ordinary), 1.25 (public), 1.5 (critical). Soil types A–D; spectral shape factor Ch(T) per soil. Base shear V = Cd(T1)·W with ductility factor Rμ and overstrength Ωu by system (e.g. RC moment frame Rμ = 4, Ωu = 1.5 for ULS).", keywords: ["nepal", "nbc 105", "seismic", "zoning factor", "kathmandu", "base shear", "earthquake"] },
  { id: "nbc205", code: "NBC 205:2012 (Nepal)", clause: "Mandatory Rules of Thumb – RC framed buildings", topic: "Minimum sizes without detailed design (≤ 3 storeys, spans ≤ 4.5 m)", text: "Columns ≥ 300 × 300 mm (M20, min 8 bars Ø16 for 3 storeys; 230 × 230 with 4 Ø16 permitted for single-storey small buildings), ties Ø8 @ 100 mm at ends / 150 mm middle; beams ≥ 230 × 325 mm (2 + 2 Ø16 min, stirrups Ø8 @ 100/150); slabs ≥ 125 mm with Ø8/Ø10 @ 150 mm; foundation depth ≥ 1.5 m on soft soil; bar lap 60 Ø. Cement grade M20 minimum, Fe415/500 steel.", keywords: ["nepal", "nbc 205", "rules of thumb", "column size", "beam size", "slab thickness", "minimum"] },
  { id: "nbc102-103", code: "NBC 102:1994 / NBC 103:1994 (Nepal)", clause: "Loads", topic: "Unit weights and imposed loads", text: "Adopt IS 875 values: RC 25 kN/m³, brick masonry 19 kN/m³; imposed loads residential 2.0 kN/m², offices 2.5–4.0, corridors/stairs 3.0–5.0, shops 4.0, storage 5.0/m height. Wind (NBC 104): basic wind speed 47 m/s in the Terai to 55 m/s in high hills.", keywords: ["nepal", "nbc 102", "nbc 103", "live load", "dead load", "wind"] },
  { id: "nbc-206-bye", code: "NBC 206:2015 / Nepal building bye-laws", clause: "Architectural rules", topic: "Room sizes, setbacks and height", text: "Habitable room ≥ 9.5 m² (width ≥ 2.4 m), kitchen ≥ 5 m², bath ≥ 1.8 m², WC ≥ 1.1 m², ceiling height ≥ 2.75 m (2.4 m in hill areas); Kathmandu Valley bye-laws: setback ≥ 1.5 m from road, ground coverage ≤ 70 % (≤ 50 % for large plots), FAR 1.75–3.5 by zone, right-of-way widening for roads < 8 m.", keywords: ["nepal", "room size", "setback", "far", "coverage", "bye law", "kathmandu"] },
  // Geotech / general
  { id: "is1904", code: "IS 1904:1986", clause: "7.2 / 7.3", topic: "Foundation depth", text: "Minimum depth of foundation 500 mm below ground (except on rock). Use Rankine formula Dmin = (q/γ)·[(1 − sin φ)/(1 + sin φ)]² for cohesionless soils. Foundation below frost line and zone of seasonal moisture change (expansive soils ≥ 1.5 m typical).", keywords: ["foundation depth", "minimum depth", "rankine"] },
  { id: "is6403", code: "IS 6403:1981", clause: "5.1", topic: "Bearing capacity", text: "qu = c·Nc·sc·dc·ic + q·Nq·sq·dq·iq + 0.5·γ·B·Nγ·sγ·dγ·iγ·W'. Shape factors: square sc = 1.3, sq = 1.2, sγ = 0.8; circular sγ = 0.6. Factor of safety 2.5–3 on net ultimate.", keywords: ["bearing capacity", "terzaghi", "shape factor", "factor of safety"] },
  { id: "is456-5.4", code: "IS 456:2000", clause: "Table 2 / 6.2.1", topic: "Concrete grades and modulus", text: "Nominal mixes (Table 9): M10 1:3:6, M15 1:2:4, M20 1:1.5:3 (M20+ should be design mix). Ec = 5000·√fck MPa. Minimum grade: M20 for RCC (mild), M25 (moderate), M30 (severe), M35 (very severe), M40 (extreme).", keywords: ["grade", "mix", "modulus", "ec", "minimum grade"] },
  { id: "is10262", code: "IS 10262:2019", clause: "5 / Table 5", topic: "Concrete mix design", text: "Target mean strength f'ck = fck + 1.65·S (S = 3.5 MPa for M10–M15, 4.0 for M20–M25, 5.0 for M30–M55). Max w/c ratio 0.55 (mild), 0.50 (moderate), 0.45 (severe), 0.40 (extreme, IS 456 Table 5). Water content 186 kg/m³ for 20 mm aggregate, slump 25–50 mm.", keywords: ["mix design", "target strength", "water cement", "w/c"] },
  { id: "irc37", code: "IRC:37-2018", clause: "3 / 6", topic: "Flexible pavement design", text: "Design traffic in msa: N = 365·A·[(1+r)^n − 1]/r · D · F (D lane distribution, F vehicle damage factor 2.5–4.5). Subgrade CBR ≥ 5% (8% desirable); effective CBR from subgrade + embankment. Design catalogues give bituminous/base/subbase thicknesses per msa and CBR.", keywords: ["pavement", "cbr", "msa", "traffic", "road"] },
  { id: "is1200", code: "IS 1200 (Parts 1–28)", clause: "General", topic: "Measurement of building works", text: "Earthwork measured in m³ (dimension to nearest 0.01 m); concrete m³; brickwork m³ (half-brick walls in m²); plastering/painting m²; steel by weight (kg, d²/162 kg/m); deductions for openings > 0.1 m² in masonry, > 0.5 m² in plaster.", keywords: ["measurement", "boq", "deduction", "quantity"] },
];

const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9 ]/g, " ");

export function searchCodes(query: string, opts: { code?: string; country?: string; limit?: number } = {}): (CodeClause & { score: number })[] {
  const terms = norm(query).split(/\s+/).filter((t) => t.length > 1);
  const results = CODE_CLAUSES.filter((c) => (!opts.code || c.code.toLowerCase().includes(opts.code.toLowerCase())) && (!opts.country || countryOf(c.code).toLowerCase() === opts.country.toLowerCase())).map((c) => {
    const hay = norm(`${c.code} ${c.clause} ${c.topic} ${c.text} ${c.keywords.join(" ")}`);
    let score = 0;
    for (const t of terms) {
      if (c.keywords.some((k) => norm(k).includes(t))) score += 3;
      if (norm(c.topic).includes(t)) score += 2;
      if (hay.includes(t)) score += 1;
    }
    return { ...c, score };
  }).filter((r) => r.score > 0).sort((a, b) => b.score - a.score || countryRank(a.code) - countryRank(b.code));
  return results.slice(0, opts.limit ?? 5);
}
