/** Public key that verifies CivilMate company licences (generated by scripts/license.mjs keygen). Safe to publish. */
export const LICENSE_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAJZPInImnuJaIeWq21L4SI8dmvB2QEDangWfGq0rJR9s=
-----END PUBLIC KEY-----`;
