#!/usr/bin/env node
/**
 * CivilMate company-edition licences (vendor tool; runs offline).
 *
 *   node scripts/license.mjs keygen
 *       Creates the signing key pair once. The PRIVATE key goes to ~/.civilmate/license-private.pem (keep it secret and
 *       backed up offline; it is never in the repository). The PUBLIC key is written to src/lib/company/license-key.ts.
 *
 *   node scripts/license.mjs issue --company "ABC Construction Ltd" --seats 25 --expires 2027-12-31
 *       Prints a licence string for the customer's administrator to paste into Admin → Company
 *       (or to set as CIVIL_AI_LICENSE). Omit --expires for a perpetual licence.
 */
import { generateKeyPairSync, createPrivateKey, sign, randomUUID } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import { homedir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const KEY_DIR = process.env.CIVILMATE_KEY_DIR || join(homedir(), ".civilmate");
const PRIVATE = join(KEY_DIR, "license-private.pem");
const PUBLIC_TS = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "lib", "company", "license-key.ts");
const b64u = (buf) => Buffer.from(buf).toString("base64").replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
const arg = (name) => { const i = process.argv.indexOf(`--${name}`); return i > 0 ? process.argv[i + 1] : undefined; };

const cmd = process.argv[2];
if (cmd === "keygen") {
  if (existsSync(PRIVATE)) { console.error(`A private key already exists at ${PRIVATE}. Refusing to overwrite it (licences issued with it would stop working).`); process.exit(1); }
  const { publicKey, privateKey } = generateKeyPairSync("ed25519");
  mkdirSync(KEY_DIR, { recursive: true, mode: 0o700 });
  writeFileSync(PRIVATE, privateKey.export({ type: "pkcs8", format: "pem" }), { mode: 0o600 });
  chmodSync(PRIVATE, 0o600);
  const pub = publicKey.export({ type: "spki", format: "pem" }).toString().trim();
  writeFileSync(PUBLIC_TS, `/** Public key that verifies CivilMate company licences (generated by scripts/license.mjs keygen). Safe to publish. */\nexport const LICENSE_PUBLIC_KEY = \`${pub}\`;\n`);
  console.log(`Private key: ${PRIVATE}  (back it up offline; never commit or share it)\nPublic key written to ${PUBLIC_TS}`);
} else if (cmd === "issue") {
  const company = arg("company"), seats = Number(arg("seats")), expires = arg("expires") ?? null;
  if (!company || !(seats > 0)) { console.error('Usage: node scripts/license.mjs issue --company "Name" --seats 25 [--expires YYYY-MM-DD]'); process.exit(1); }
  if (expires && !/^\d{4}-\d{2}-\d{2}$/.test(expires)) { console.error("--expires must be YYYY-MM-DD"); process.exit(1); }
  if (!existsSync(PRIVATE)) { console.error(`No private key at ${PRIVATE}. Run: node scripts/license.mjs keygen`); process.exit(1); }
  const payload = { v: 1, id: randomUUID(), company, seats, issued: new Date().toISOString().slice(0, 10), expires };
  const head = `CM1.${b64u(JSON.stringify(payload))}`;
  const sig = sign(null, Buffer.from(head), createPrivateKey(readFileSync(PRIVATE)));
  console.log(`${head}.${b64u(sig)}`);
} else {
  console.log("Usage:\n  node scripts/license.mjs keygen\n  node scripts/license.mjs issue --company \"Name\" --seats 25 [--expires YYYY-MM-DD]");
}
